name: qmenta_1000_brains
channels: 
  - conda-forge
dependencies:
  - python=3.6
  - nomkl
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - pandas
  - jupyter
  - jupyterlab
  - tqdm
  - pip:
    - qmenta-client