name: qmenta_1000_brains
channels: 
  - conda-forge
dependencies:
  - python=2.7
  - pip=10.0.1
  - nomkl
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - pandas
  - jupyter
  - jupyterlab
  - tqdm
  - pylint
  - pip:
    - --extra-index-url https://testpypi.python.org/pypi
    - qmenta-sdk-lib
    - qmenta-client
